# simple Dockerfile for backend
FROM python:3.11-slim

WORKDIR /app
COPY ./backend /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1
ENV MONGO_URI=mongodb://mongo:27017

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
